Add correct quoting, remove extra shells spawned Cache results

diff --git a/dt_stat b/dt_stat
--- a/dt_stat
+++ b/dt_stat
@@ -2,7 +2,6 @@
 
 # author: Frank Rowand  frank.rowand@sonymobile.com
 # license: GPL V2
-
 #_______________________________________________________________________________
 
 script=`basename $0`
@@ -16,56 +15,49 @@ cmd_nd=0
 cmd_nxb=0
 cmd_nxd=0
 
+if [ $# -eq 0 ] ; then
+	help=1
+fi
 
 while [[ $# -gt 0 ]] ; do
+	ARG=${1:1}
 
-	case $1 in
-
-		-h | -help | --help )
+	case "$ARG" in
+		h | -help)
 			help=1
-			shift $#
+			break
 			;;
-
-		--d )
+		"d")
 			cmd_d=1
 			shift
 			;;
-
-		--n )
+		"n")
 			cmd_n=1
 			shift
 			;;
-
-		--nb )
+		"nb")
 			cmd_nb=1
 			shift
 			;;
-
-		--nd )
+		"nd")
 			cmd_nd=1
 			shift
 			;;
-
-		--nxb)
+		"nxb")
 			cmd_nxb=1
 			shift
 			;;
-
-		--nxd )
+		"nxd")
 			cmd_nxd=1
 			shift
 			;;
-
-		* )
-			break
+		*)
+			echo "ERROR: invalid parameter" 1>&2
+			exit 1
 			;;
 	esac
 
 done
-
-if [ $# -gt 0 ] ; then
-	help=1
-fi
 
 
 #_______________________________________________________________________________
@@ -76,42 +68,37 @@ PDT="/proc/device-tree/"
 #_______________________________________________________________________________
 
 if [[ ${help} -eq 1 ]] ; then
+	cat<<EOF 1>&2
 
-echo ""                                                                      >&2
-echo "usage:"                                                                >&2
-echo "   ${script}"                                                          >&2
-echo ""                                                                      >&2
-echo "      -h         synonym for --help"                                   >&2
-echo "      -help      synonym for --help"                                   >&2
-echo "      --help     print this message and exit"                          >&2
-echo ""                                                                      >&2
-echo "      --d        report devices"                                       >&2
-echo "      --n        report nodes"                                         >&2
-echo "      --nb       report nodes bound to a driver"                       >&2
-echo "      --nd       report nodes with a device"                           >&2
-echo "      --nxb      report nodes not bound to a driver"                   >&2
-echo "      --nxd      report nodes without a device"                        >&2
-echo ""                                                                      >&2
-echo "   Reports about nodes in ${PDT}"                                      >&2
-echo "   Nodes without a compatible string are not reported"                 >&2
-echo ""                                                                      >&2
-echo "   data fields reported:"                                              >&2
-echo "      --d        Device Node"                                          >&2
-echo "      --n        Node Compatible"                                      >&2
-echo "      --nb       Node Compatible"                                      >&2
-echo "      --nd       Node Compatible Device Driver"                        >&2
-echo "      --nxb      Node Compatible"                                      >&2
-echo "      --nxd      Node Compatible"                                      >&2
-echo ""                                                                      >&2
+usage:
+   dt_stat
 
-exit 1
+      -h         synonym for --help
+      --help     print this message and exit
 
+      -d        report devices
+      -n        report nodes
+      -nb       report nodes bound to a driver
+      -nd       report nodes with a device
+      -nxb      report nodes not bound to a driver
+      -nxd      report nodes without a device
+
+   Reports about nodes in /proc/device-tree/
+   Nodes without a compatible string are not reported
+
+   data fields reported:
+      -d        Device Node
+      -n        Node Compatible
+      -nb       Node Compatible
+      -nd       Node Compatible Device Driver
+      -nxb      Node Compatible
+      -nxd      Node Compatible
+EOF
+	exit 1
 fi
 
 
 #_______________________________________________________________________________
-
-
 if [[ ! -d /sys/devices ]] ; then
 	echo "ERROR: /sys/devices is not a directory"                                >&2
 	exit 1
@@ -123,38 +110,60 @@ if [[ ! -d ${PDT} ]] ; then
 	exit 1
 fi
 
-
 # ==============================================================================
 # COLLECT DATA
 
-#-----  nodes of devices with an OF_FULLNAME in uevent
-
-nodes_dev=$(
-	for dev in `find /sys/devices -name uevent`; do
-		grep '^OF_FULLNAME=' ${dev} | sed -e 's|OF_FULLNAME=||'
-	done | sort
-	)
-
+UEVENTS="$(find /sys/devices -name uevent -type f)"
 
 #-----  nodes with a device that has been bound to a driver
 
-nodes_dev_bound=$(
-	for uevent in `find /sys/devices -name uevent`; do
-		if [[ -d $(dirname ${uevent})/driver ]]; then
-			grep '^OF_FULLNAME=' ${uevent} | sed -e 's|OF_FULLNAME=||'
+#-----  nodes of devices with an OF_FULLNAME in uevent
+NODES_DEV=""
+function get_nodes_dev() {
+	for dev in $UEVENTS; do
+		grep '^OF_FULLNAME=' "${dev}" | sed -e 's|OF_FULLNAME=||'
+	done | sort
+}
+function nodes_dev() {
+	if [ -z "$NODES_DEV" ]; then
+		NODES_DEV="$(get_nodes_dev)"
+	fi
+	echo "$NODES_DEV"
+}
+
+NODES_DEV_BOUND=""
+function get_nodes_dev_bound() {
+	for uevent in $UEVENTS; do
+		if [[ -d $(dirname "${uevent})/driver") ]]; then
+			grep '^OF_FULLNAME=' "${uevent}" | sed -e 's|OF_FULLNAME=||'
 		fi
 	done | sort
-	)
+}
 
+function nodes_dev_bound() {
+	if [ -z "$NODES_DEV_BOUND" ]; then
+		NODES_DEV_BOUND="$(get_nodes_dev_bound)"
+	fi
+	echo "$NODES_DEV_BOUND"
+}
 
 #-----  nodes with a compatible property
-
-nodes_compatible=$( \
-	for node in `find ${PDT} -name compatible`; do
-		echo $(dirname ${node}) | sed -e 's|\/proc\/device-tree||'
+NODES_COMPAT=""
+function get_nodes_compat() {
+	local D
+	for node in `find "${PDT}" -name compatible -type f`; do
+		D=$(dirname "${node}")
+		echo "$D" | sed -e 's|\/proc\/device-tree||'
 	done | sort
-	)
+}
+function nodes_compat() {
+	if [ -z "$NODES_COMPAT" ]; then
+		NODES_COMPAT="$(get_nodes_compat)"
+	fi
+	echo "$NODES_COMPAT"
+}
 
+TABS='		'
 
 # ==============================================================================
 # REPORTS
@@ -162,20 +171,21 @@ nodes_compatible=$( \
 #-----  devices with an OF_FULLNAME in uevent
 
 if [[ ${cmd_d} -eq 1 ]] ; then
-	for dev in `find /sys/devices -name uevent`; do
-		if grep -q '^OF_FULLNAME' ${dev} ; then
-			node=$(grep '^OF_FULLNAME' ${dev} | sed -e 's|OF_FULLNAME=||')
-			echo $(dirname ${dev}) ${node}
+	for dev in $UEVENTS; do
+		if grep -q '^OF_FULLNAME' "${dev}" ; then
+			node=$(grep '^OF_FULLNAME' "${dev}" | sed -e 's|OF_FULLNAME=||')
+			echo $(dirname "${dev}") $TABS "${node}"
 		fi
 	done | sort
 fi
 
-
 #-----  nodes with a compatible property
 
 if [[ ${cmd_n} -eq 1 ]] ; then
-	for node in ${nodes_compatible} ; do
-		echo ${node} $(cat ${PDT}/${node}/compatible)
+	for node in $(nodes_compat) ; do
+		if [ -f "${PDT}/${node}/compatible" ]; then
+			echo "$node" $TABS $(< "${PDT}/${node}/compatible")
+		fi
 	done
 fi
 
@@ -183,8 +193,8 @@ fi
 #-----  nodes with device bound to driver
 
 if [[ ${cmd_nb} -eq 1 ]] ; then
-	for node in ${nodes_dev_bound} ; do
-		echo ${node} $(cat ${PDT}/${node}/compatible)
+	for node in $(nodes_dev_bound) ; do
+		echo "${node}" $TABS $(< "${PDT}/${node}/compatible")
 	done
 fi
 
@@ -192,15 +202,14 @@ fi
 #-----  nodes with a device
 
 if [[ ${cmd_nd} -eq 1 ]] ; then
-	for uevent in `find /sys/devices -name uevent`; do
+	for uevent in $UEVENTS; do
 		if [[ -d $(dirname ${uevent})/driver ]]; then
-			node=$(  grep '^OF_FULLNAME=' ${uevent} | sed -e 's|OF_FULLNAME=||')
+			node=$(grep '^OF_FULLNAME=' ${uevent} | sed -e 's|OF_FULLNAME=||')
 			if [[ "${node}" != "" ]] ; then
 				dev=$(dirname ${uevent})
 				# driver might be empty
-				driver=$(grep '^DRIVER=' ${uevent} | sed -e 's|DRIVER=||' )
-				compatible=$(cat ${PDT}/${node}/compatible)
-				echo ${node} ${compatible} ${dev} ${driver}
+				driver=$(grep '^DRIVER=' ${uevent} | sed -e 's|DRIVER=||')
+				echo "$node" $TABS $(< "${PDT}/${node}/compatible") $TABS "$dev" $TABS "$driver"
 			fi
 		fi
 	done | sort
@@ -210,9 +219,9 @@ fi
 #-----  nodes not bound to a driver
 
 if [[ ${cmd_nxb} -eq 1 ]] ; then
-	for node in ${nodes_compatible}; do
-		if ! echo ${nodes_dev_bound} | grep -E -q "(^| )${node}( |\$)"; then
-			echo ${node} $(cat ${PDT}/${node}/compatible)
+	for node in $(nodes_compat); do
+		if ! echo $(nodes_dev_bound) | grep -E -q "(^|)${node}( |\$)"; then
+			echo "${node}" $TABS $(< "${PDT}/${node}/compatible")
 		fi
 	done
 fi
@@ -221,9 +230,9 @@ fi
 #-----  nodes without a device
 
 if [[ ${cmd_nxd} -eq 1 ]] ; then
-	for node in ${nodes_compatible}; do
-		if ! echo ${nodes_dev} | grep -E -q "(^| )${node}( |\$)"; then
-			echo ${node} $(cat ${PDT}/${node}/compatible)
+	for node in $(nodes_compat); do
+		if ! echo ${nodes_dev} | grep -E -q "(^|)${node}( |\$)"; then
+			echo "${node}" $TABS $(< "${PDT}/${node}/compatible")
 		fi
 	done
 fi
